# Generated by Django 4.2.5 on 2023-10-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
