# Generated by Django 4.2.5 on 2023-10-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_filling'),
        ('shop', '0003_filling_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filling',
        ),
    ]
