# Generated by Django 4.2.5 on 2023-10-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_art_remove_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='category',
        ),
        migrations.AddField(
            model_name='types',
            name='category',
            field=models.ManyToManyField(related_name='category', to='shop.category'),
        ),
    ]
