# Generated by Django 4.2.5 on 2023-10-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_types_category_types_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='category',
        ),
        migrations.AlterField(
            model_name='types',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AddField(
            model_name='types',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='shop.category'),
            preserve_default=False,
        ),
    ]
