# Generated by Django 4.2.5 on 2023-10-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='Hello',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
