# Generated by Django 4.2.5 on 2023-10-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_types_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='types',
            name='category',
        ),
        migrations.AddField(
            model_name='types',
            name='category',
            field=models.ManyToManyField(related_name='category', to='shop.category'),
        ),
    ]
