# Generated by Django 4.2.5 on 2023-10-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_types_slug_remove_types_category_types_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='category',
        ),
        migrations.AddField(
            model_name='types',
            name='categories',
            field=models.ManyToManyField(related_name='types', to='shop.category'),
        ),
    ]
