# Generated by Django 4.2.5 on 2023-10-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='svg',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
